/**
 * Frame counts for the canvas scrub tier.
 *
 * The hero deliberately has NO sequence. It is an Apple-style one-shot film that
 * plays through once on load and is not scroll-driven, so scrubbing it would be
 * wrong as well as wasteful. The colours rotate carries the scrub instead.
 *
 * Generated by tools/build-assets.ps1, which also writes
 * public/frames/manifest.json. Kept as typed constants rather than fetched at
 * runtime so a scrub section never waits on a manifest request before it can
 * start loading; the manifest exists so a drifted count is caught in review.
 *
 * Wave 2 added display, a20-pro and pro-vs-promax: three PLAY sections that
 * were promoted to scroll-scrub after review, so they run backwards when the
 * visitor does.
 */
export const FRAME_COUNTS = {
  colors: 56,
  display: 56,
  'camera-sensor': 104,
  'a20-pro': 120,
  'pro-vs-promax': 48,
  'duo-hero': 100,
  'duo-colors': 64,
  fold: 120,
} as const;

/**
 * `/frames`, `/video`, `/poster` are `immutable`. Replacing a file in place
 * does not change its URL, so a returning tab keeps the old bytes. Bump this
 * when Display (or any) sequence is regenerated locally.
 */
export const MEDIA_REV = 'c4f9b2';

/**
 * ဖိုင်များထဲမှ ဘယ်ဖရိမ်ကစပြီး ဖွင့်မလဲ (0-based)။
 *
 * Display ကို unique window ဖြင့် ပြန်ထုတ်ပြီးနောက် (`three to info` ၏
 * 3.00s–6.25s) colors ရှေ့ပိုင်းကို ဖိုင်ထဲမထည့်တော့သဖြင့် offset မလို။
 * ပြန်ထည့်ရင် FRAME_COUNTS နှင့် ဖိုင်အရေအတွက်ကို တူအောင်ပြင်ပါ။
 *
 * `/frames` သည် `immutable` ဖြင့် serve လုပ်ထားသဖြင့် (next.config.mjs)
 * ဖိုင်အမည်တူပြီး အကြောင်းအရာပြောင်းလျှင် ပြန်လာသောဧည့်သည်က cache ဟောင်းကိုရမည်။
 */
export const FRAME_STARTS: Partial<Record<ScrubSlug, number>> = {};

/** Frames actually played, after the start offset. */
export function playedFrames(slug: ScrubSlug): { start: number; count: number } {
  const start = FRAME_STARTS[slug] ?? 0;
  return { start, count: FRAME_COUNTS[slug] - start };
}

/**
 * Output size of every native clip in /public/video, as written by
 * tools/build-assets.ps1 and confirmed with ffprobe.
 *
 * These are the desktop/tablet files. The lite tier fetches a 1280-wide sibling
 * (`slug-1280.mp4`) whose aspect ratio matches, so the stacked mobile layout
 * keeps using this table. Every clip including the hero has that sibling.
 *
 * Heights vary because five clips are cropped to clear a watermark band
 * (docs/ASSET_INVENTORY.md §1). `duo-transition` plays `rotate.mp4`: a 16:9
 * unfold cut (1920×1080) from the YouTube Duo plate, not the 2:1 Duo-colours
 * turn. Only the RATIO is consumed, by that stacked layout, where a film is
 * shown at its own aspect instead of being cover-cropped into a portrait
 * viewport.
 */
export const CLIP_SIZE = {
  hero: [3840, 2160],
  colors: [2560, 1440],
  display: [2560, 1440],
  'pro-vs-promax': [2560, 1440],
  design: [1920, 806],
  'dynamic-island': [2880, 1440],
  'camera-sensor': [2880, 1440],
  'camera-penetration': [2880, 1208],
  aperture: [1920, 806],
  'a20-pro': [2880, 1440],
  'c2-modem': [2880, 1440],
  battery: [2880, 1208],
  'duo-transition': [1920, 1080],
  'duo-hero': [2880, 1440],
  fold: [2880, 1440],
  thickness: [2880, 1208],
  'duo-touch': [2880, 1440],
  'duo-colors': [2880, 1440],
} as const satisfies Record<string, readonly [number, number]>;

export type ClipSlug = keyof typeof CLIP_SIZE;
export type ScrubSlug = Extract<ClipSlug, keyof typeof FRAME_COUNTS>;

/** CSS `aspect-ratio` value for a clip, e.g. "2880 / 1440". */
export function clipAspect(slug: ClipSlug): string {
  const [w, h] = CLIP_SIZE[slug];
  return `${w} / ${h}`;
}

/**
 * The same ratio as a bare number, for CSS that has to size a clip against the
 * VIEWPORT HEIGHT rather than its container's width. `aspect-ratio` alone
 * cannot do that: with a definite width it derives the height, and a
 * `max-height` then crops rather than narrowing the box.
 */
export function clipRatio(slug: ClipSlug): number {
  const [w, h] = CLIP_SIZE[slug];
  return w / h;
}

/**
 * Phones get their own encode of every clip.
 *
 * A 390px viewport at 3x is 1170 device pixels, and it was being sent the same
 * 2880px file a desktop gets — measured, a full scroll of the page on a phone
 * fetched 26.5MB of video, and phones are also where the network is worst. The
 * 1280 encode is 71% smaller at SSIM 0.995 (battery, All): these are smooth 3D
 * renders with no fine texture, so they survive the downscale where a photograph
 * would not.
 *
 * The width is in the filename on purpose. Every media directory is served
 * `immutable`, so re-encoding at a different width has to produce a different
 * name — see the cache contract in the README.
 *
 * The hero has a 1280 sibling too. On the lite (phone) tier the preloader
 * opens on the poster (`preload="none"`) and `Hero` plays `hero-1280.mp4`
 * after the curtain — phones never pull the 4K file. Desktop/tablet still
 * wait on the native clip buffering so the title card stays sharp.
 */
export type ClipVariant = 'full' | 'mobile';

export const MOBILE_CLIP_WIDTH = 1280;

/**
 * Slug နှင့် ဖိုင်အမည် မတူသော clip များ။
 *
 * Display ၏ delivery ဖိုင်သည် `display-panel` — source `three to info` မှ
 * unique 3.25s (ဖုန်းသုံးလုံး → 6.9″ panel) ကို ဖြတ်ထားသည်။ Colors ရှေ့ပိုင်း
 * နှင့် 48MP camera အမြီး မပါ။
 *
 * `duo-transition` ၏ delivery ဖိုင်သည် `rotate` — YouTube Duo 1080p မှ
 * 1.00s–13.00s cut (12s၊ အသံမပါ)။ Intro၊ Duo title၊ လက်ထဲ ဖွင့်ပြ အထိ။
 * Slug `duo-transition` နှင့် ဖိုင်အမည် `rotate` ကို ထိန်းထားသည်: tests နှင့်
 * immutable `/video` cache contract က ဒီ URL ကို မျှော်လင့်သည်။ Fold
 * section က `fold.mp4` ကို သီးသန့် scrub အဖြစ် ဆက်သုံးသည်။
 *
 * ဖိုင်အမည်အသစ်ဖြစ်ရသည်မှာ မဖြစ်မနေလိုအပ်ချက်ဖြစ်သည်: /video သည် `immutable`
 * ဖြင့် serve လုပ်ထားသဖြင့် အမည်ဟောင်းကို အကြောင်းအရာအသစ်ဖြင့်အစားထိုးလျှင်
 * ပြန်လာသောဧည့်သည်သည် clip ဟောင်းကိုပင် ဆက်ရနေမည် — width ကို ဖိုင်အမည်တွင်
 * ထည့်ရသည့် အကြောင်းရင်းအတိုင်းပင်။
 */
const CLIP_FILES: Partial<Record<ClipSlug, string>> = {
  display: 'display-panel',
  'duo-transition': 'rotate',
};

const clipFile = (slug: ClipSlug): string => CLIP_FILES[slug] ?? slug;

/** Native file on `full`; `slug-1280.mp4` on `mobile`. Both exist for every clip. */
export const videoSrc = (slug: ClipSlug, variant: ClipVariant = 'full') => {
  const file =
    variant === 'mobile'
      ? `/video/${clipFile(slug)}-${MOBILE_CLIP_WIDTH}.mp4`
      : `/video/${clipFile(slug)}.mp4`;
  return `${file}?v=${MEDIA_REV}`;
};

export const posterSrc = (slug: ClipSlug) => `/poster/${slug}.jpg?v=${MEDIA_REV}`;
